# Generated by Django 4.0.5 on 2022-06-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_type_product_product_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Color',
            new_name='Product_color',
        ),
    ]
