# Generated by Django 4.0.5 on 2022-06-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_color_product_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Date_uploaded',
            new_name='date_uploaded',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_color',
            new_name='product_color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_type',
            new_name='product_type',
        ),
    ]
